[ko]
languageName = "Korean"
weight = 10
[ko.params]
footer = 'Powered by <a class="text-muted" target="_blank" href="https://github.com/gethyas/doks">Doks</a>'
languageISO = "KO"
languageTag = "ko-KR"
